version: '3'
services:

#up order: nginx-proxy-manager, jackett, Deluge, sonnar, radarr

#nginx-proxy-manager container configuration
  nginx-proxy-manager:
    container_name: $NGINXPROXYMANAGER_CONTAINER_NAME
    image: 'jc21/nginx-proxy-manager:latest'
    ports:
      - '80:80'
      - '443:443'
      - '81:81'
    restart: unless-stopped
    volumes:
     - '$LOCAL_MOUNTED_VOLUME_DOCKERAPPDATA/$NGINXPROXYMANAGER_CONTAINER_NAME:/data'
     - '$LOCAL_MOUNTED_VOLUME_DOCKERAPPDATA/letsencrypt:/etc/letsencrypt'
     - '$LOCAL_MOUNTED_VOLUME_DOCKERAPPDATA/webfileserver:/www/'
     - '$LOCAL_MOUNTED_VOLUME_NONCRITICALDATA/media/movies:/www/files.blasi.io/movies'
     - '$LOCAL_MOUNTED_VOLUME_NONCRITICALDATA/media/series:/www/files.blasi.io/series'

#Jackett container settings
  jackett:
    image: lscr.io/linuxserver/jackett:latest
    container_name: $JACKETT_CONTAINER_NAME
    environment:
      - PUID=111
      - PGID=321
      - UMASK=002
      - TZ=America/Sao_Paulo
      - AUTO_UPDATE=true
    volumes:
      - '$LOCAL_MOUNTED_VOLUME_DOCKERAPPDATA/$JACKETT_CONTAINER_NAME:/config'
      - '$LOCAL_MOUNTED_VOLUME_NONCRITICALDATA/torrents:/noncriticaldata/torrents'
    logging:
      driver: json-file
    network_mode: bridge
    ports:
      - 9117:9117
    restart: unless-stopped
    depends_on:
      - $NGINXPROXYMANAGER_CONTAINER_NAME


#Deluge container settings
  deluge:
    image: ghcr.io/linuxserver/deluge:latest
    container_name: $DELUGE_CONTAINER_NAME
    environment:
      - PUID=222
      - PGID=321
      - UMASK=002
      - TZ=America/Sao_Paulo
      - DELUGE_LOGLEVEL=error
    volumes:
      - '$LOCAL_MOUNTED_VOLUME_DOCKERAPPDATA/$DELUGE_CONTAINER_NAME:/config'
      - '$LOCAL_MOUNTED_VOLUME_NONCRITICALDATA/torrents:/noncriticaldata/torrents'
    logging:
      driver: json-file
    network_mode: bridge
    ports:
      - 8112:8112
      - 6881:6881
      - 6881:6881/udp
    restart: unless-stopped
    depends_on:
      - $NGINXPROXYMANAGER_CONTAINER_NAME
      - $JACKETT_CONTAINER_NAME

#Sonarr container settings
  sonarr:
    image: ghcr.io/linuxserver/sonarr:latest
    container_name: $SONARR_CONTAINER_NAME
    environment:
      - PUID=333
      - PGID=321
      - UMASK=002
      - TZ=America/Sao_Paulo
    volumes:
      - '$LOCAL_MOUNTED_VOLUME_DOCKERAPPDATA/$SONARR_CONTAINER_NAME:/config'
      - '$LOCAL_MOUNTED_VOLUME_NONCRITICALDATA:/noncriticaldata'
    logging:
      driver: json-file
    network_mode: bridge
    ports:
      - 8989:8989
    restart: unless-stopped
    depends_on:
      - $NGINXPROXYMANAGER_CONTAINER_NAME
      - $JACKETT_CONTAINER_NAME
      - $DELUGE_CONTAINER_NAME

#Radarr container settings
  radarr:
    image: ghcr.io/linuxserver/radarr:latest
    container_name: $RADARR_CONTAINER_NAME
    environment:
      - PUID=444
      - PGID=321
      - UMASK=002
      - TZ=America/Sao_Paulo
    volumes:
      - '$LOCAL_MOUNTED_VOLUME_DOCKERAPPDATA/$RADARR_CONTAINER_NAME:/config'
      - '$LOCAL_MOUNTED_VOLUME_NONCRITICALDATA:/noncriticaldata'
    logging:
      driver: json-file
    network_mode: bridge
    ports:
      - 7878:7878
    restart: unless-stopped
    depends_on:
      - $NGINXPROXYMANAGER_CONTAINER_NAME
      - $JACKETT_CONTAINER_NAME
      - $DELUGE_CONTAINER_NAME
      - $SONARR_CONTAINER_NAME
