#!/bin/bash
LOCAL_MOUNTED_VOLUME_DOCKERAPPDATA='/srv/docker_appdata/dev'
MARIADB_CONTAINER_NAME=mariadb
WORDPRESS_CONTAINER_NAME=wordpress

#$MARIADB folder
if [ -d "$LOCAL_MOUNTED_VOLUME_DOCKERAPPDATA/$MARIADB_CONTAINER_NAME/" ]; then
    echo "apagando $LOCAL_MOUNTED_VOLUME_DOCKERAPPDATA/$MARIADB_CONTAINER_NAME/"
    rm -r "$LOCAL_MOUNTED_VOLUME_DOCKERAPPDATA/$MARIADB_CONTAINER_NAME/"
else
    echo $LOCAL_MOUNTED_VOLUME_DOCKERAPPDATA/$MARIADB_CONTAINER_NAME" folder does not exists.. creating..."
fi
mkdir "$LOCAL_MOUNTED_VOLUME_DOCKERAPPDATA/$MARIADB_CONTAINER_NAME"
chown -R 1001:1001 "$LOCAL_MOUNTED_VOLUME_DOCKERAPPDATA/$MARIADB_CONTAINER_NAME/"
chmod o+w "$LOCAL_MOUNTED_VOLUME_DOCKERAPPDATA/$MARIADB_CONTAINER_NAME/"

#$WORDPRESS folder
if [ -d "$LOCAL_MOUNTED_VOLUME_DOCKERAPPDATA/$WORDPRESS_CONTAINER_NAME" ]; then
    echo "apagando $LOCAL_MOUNTED_VOLUME_DOCKERAPPDATA/$WORDPRESS_CONTAINER_NAME"
    rm -r "$LOCAL_MOUNTED_VOLUME_DOCKERAPPDATA/$WORDPRESS_CONTAINER_NAME/"
else
    echo $LOCAL_MOUNTED_VOLUME_DOCKERAPPDATA/$WORDPRESS_CONTAINER_NAME" folder does not exists.. creating..."
fi
mkdir "$LOCAL_MOUNTED_VOLUME_DOCKERAPPDATA/$WORDPRESS_CONTAINER_NAME"
chown -R 1001:1001 "$LOCAL_MOUNTED_VOLUME_DOCKERAPPDATA/$WORDPRESS_CONTAINER_NAME/"
chmod o+w "$LOCAL_MOUNTED_VOLUME_DOCKERAPPDATA/$WORDPRESS_CONTAINER_NAME/"